### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by MaddieMewmews** [uppfinnarn/dca#1]
I'm new to cmake and after typing the compiling instructions the command prompt says, "make is not a command" Please help or provide a compiled version under releases.

**Comment by liclac** [comment]
Please install `make`. It's in `base-devel` on Arch, `build-essential` on Ubuntu, etc.

**Comment by MaddieMewmews** [comment]
Thanks so much, my Airhorn bot fork can actually work now!
